//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingRatesDemos.Resources.Translates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShippingRatesDemos.Resources.Translates.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app lets you create addresses and quote shipping rates using Shippo’s API (Test Mode)..
        /// </summary>
        internal static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Rates Demo.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofill sample.
        /// </summary>
        internal static string BtnAutofill {
            get {
                return ResourceManager.GetString("BtnAutofill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string BtnCreateAddress {
            get {
                return ResourceManager.GetString("BtnCreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to create address.
        /// </summary>
        internal static string BtnNavToCreateAddress {
            get {
                return ResourceManager.GetString("BtnNavToCreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote rates.
        /// </summary>
        internal static string BtnRates {
            get {
                return ResourceManager.GetString("BtnRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the form below to create an address in Shippo Test Mode..
        /// </summary>
        internal static string CreateAddressDesc {
            get {
                return ResourceManager.GetString("CreateAddressDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Address.
        /// </summary>
        internal static string PageCreateAddressTitle {
            get {
                return ResourceManager.GetString("PageCreateAddressTitle", resourceCulture);
            }
        }
    }
}
